
---
type: blog
date: 2018-03-12
title: "Fertility Treatment: The Educated Consumer"
image: embryo.jpg
content:
  - "Beware of the fertility clinics’ practices and protections. Read the contract carefully looking for language that would relieve the clinic of responsibility for destruction of embryos and eggs. Ask before you sign the contract with the fertility clinic:"
  - 1. How they assure that you will receive your embryo and not that of someone else;
  - 2. How they protect your frozen embryos and/or eggs from thawing and becoming unusable;
  - 3. What representations they make concerning successful IUI, IVF, ICSI and egg and embryo freezing;
  - 4. What their rate of success is respecting pregnancy with live birth as outcome;
  - 5. What their failure rate is with IUI, IVF, ICSI;
  - 6. How many clients have made claims against them for anything;
  - 7. How many times they have been sued as a clinic or with respect to an individual physician or embryologist;
  - 8. What are the qualifications of their embryologist;
  - 9. Do they recommend sperm banks or egg donor banks and, if so, do they have a
  - financial interest in the banks they recommend.
  - There are many other avenues of inquiry. Make sure you are an educated consumer
  - because fertility treatment is extremely expensive, financially and emotionally.
