---
url: https://hershlaw.com/
title: Hersh & Hersh - Personal attention - Passionate representation
description: Personal attention - Passionate representation
keywords: keywords, missing, need them
trackingID: UA-77897768-1
share: img/share.jpg
repo: http://www.github.com/acidjazz/hersh
facebook: https://www.facebook.com/Hersh-Hersh-PC-126713607354462/
twitter: http://www.twitter.com/hershandhersh
phone: 18004415545
