---
- link: http://www.nbcnews.com/news/us-news/sperm-bank-xytex-corp-sued-after-donor-details-emerge-7-n345171
  iframe:  <iframe src="http://www.nbcnews.com/widget/video-embed/431285315683" width="560" height="315" frameborder="0" allowfullscreen></iframe>
  title: Couple Sues Sperm Bank After Sketchy-Donor Details Emerge Seven Years Later
- link: http://www.usatoday.com/story/news/nation/2016/04/15/sperm-banks-perfect-donor-mentally-ill-felon-who-fathered-36-kids/83075224/
  title: Sperm bank's 'perfect donor' was a mentally ill felon who fathered 36 kids
