---
- link: https://www.law360.com/articles/1025870/clinics-may-eye-quick-deals-in-lost-embryo-cases
  title: Clinics May Eye Quick Deals In Lost Embryo Cases
- link: https://www.thestar.com/news/canada/2016/10/07/new-standards-will-tighten-rules-governing-sperm-and-egg-banks.html
  image: https://www.thestar.com/content/dam/thestar/news/canada/2016/10/07/new-standards-will-tighten-rules-governing-sperm-and-egg-banks/angie-collins.jpg.size.custom.crop.1086x721.jpg
  title: New standards will tighten rules governing sperm and egg banks
- link: http://www.nbcnews.com/news/us-news/sperm-bank-xytex-corp-sued-after-donor-details-emerge-7-n345171
  iframe:  <iframe src="http://www.nbcnews.com/widget/video-embed/431285315683" frameborder="0" width="100%" height="340px" allowfullscreen></iframe>
  title: Couple Sues Sperm Bank After Sketchy-Donor Details Emerge Seven Years Later
- link: http://www.usatoday.com/story/news/nation/2016/04/15/sperm-banks-perfect-donor-mentally-ill-felon-who-fathered-36-kids/83075224/
  title: Sperm bank's 'perfect donor' was a mentally ill felon who fathered 36 kids
